Package.describe({
  name: "deanius:package-linter",
  summary: "Description of package amazingness",
  version: "0.1.0",
  git: "https://github.com/deanius/meteor-sandbox"
});

Package.onUse(function(api) {
  // Meteor releases below this version are not supported
  api.versionsFrom("1.1.0.3");

  // Core packages and 3rd party packages
  api.use("ddp");
  api.use("tracker");
  api.use("promise");


  // The files of this package
  api.addFiles("server/index.js", ["server"]);


  // The variables that become global for users of your package
  api.export("log", ["server"]);
});


Npm.depends({
  "localeval": "15.2.3"
});


Package.onTest(function (api) {
  api.use("tinytest");
  api.use("deanius:sandbox");
  api.addFiles("tests/server/index.js", ["server"]);
});

/* Generated by okgrow:package-kitchen */
