Tinytest.add("Exports PackageModel as a function", function (test) {
  test.equal(true, _.isFunction(PackageModel));
});

var exampleFile1 = `Package.describe({
  name: "okgrow:lint-test",
  summary: "Description of package amazingness",
  version: "0.1.0",
  git: "https://github.com/deanius/meteor-sandbox"
});
Package.onUse(function(api) {
  // Meteor releases below this version are not supported
  api.versionsFrom("1.1.0.3");

  // Core packages and 3rd party packages
  api.use("ddp");
  api.use("okgrow:promise@=0.9.3", "client");

  // look, ma, no version declared:
  api.use("okgrow:router-autoscroll", ["client", "server"], {weak: true});

  api.imply("http");

  api.addFiles("shared/index.js", ["client", "server"]);
  api.addFiles("shared/index2.js");
});


Package.onTest(function (api) {
  api.use("tinytest");
  api.use("deanius:new-package");
  api.addFiles("tests/shared/index.js", ["client", "server"]);
});

/* Generated by okgrow:package-kitchen */
`;

var expectedModel1 = {
  "description": {
    "name": "okgrow:lint-test",
    "summary": "Description of package amazingness",
    "version": "0.1.0",
    "git": "https://github.com/deanius/meteor-sandbox"
  },
  "versionsFrom": "1.1.0.3",
  "coreDeps": {
    "uses": {
      "ddp": {
        "name": "ddp",
        "versionSpec": null,
        "versionNum": null,
        "versionIsExact": false
      }
    },
    "implies": {
      "http": {
        "name": "http",
        "versionSpec": null,
        "versionNum": null,
        "versionIsExact": false
      }
    }
  },
  "externalDeps": {
    "uses": {
      "okgrow:promise": {
        "name": "okgrow:promise",
        "versionSpec": "@=0.9.3",
        "versionNum": "0.9.3",
        "versionIsExact": true,
        "arch": [
          "client"
        ]
      },
      "okgrow:router-autoscroll": {
        "name": "okgrow:router-autoscroll",
        "versionSpec": null,
        "versionNum": null,
        "versionIsExact": false,
        "arch": [
          "client",
          "server"
        ],
        "options": {
          "weak": true
        }
      }
    },
    "implies": {}
  },
  "files": {
    "shared/index.js": {
      "arch": [
        [
          "client",
          "server"
        ]
      ]
    },
    "shared/index2.js": {}
  },
  "exports": {}
};

Tinytest.add("Example File 1", function (test) {
  var actualModel = new PackageModel(exampleFile1);
  test.equal(JSON.stringify(actualModel, null, 2), JSON.stringify(expectedModel1, null, 2));
});

// Tinytest.add("Example File 2", function (test) {
//   test.equal(true, true);
// });
